### ISSUE TITLE
Help this guy

### ISSUE THREAD

**Issue by NTDCore** [7GrandDadPGN/VapeLiteForRoblox#5]
https://media.discordapp.net/attachments/1216952075766992896/1223887136366006313/Screenshot_20240331_134229_Discord.jpg?ex=661b7cb8&is=660907b8&hm=1598bea4a819d5f13fff70c60f7a312b1d89a8594cb948e05f16c01436c240e5&
https://media.discordapp.net/attachments/1216952075766992896/1223887136596688896/Screenshot_20240331_134254_Discord.jpg?ex=661b7cb8&is=660907b8&hm=28f1a80a20e3001a9409a331d75949d4b8426bd7e0ccbf6b14734acd556ee6d1&
https://media.discordapp.net/attachments/1216952075766992896/1223887136793690183/Screenshot_20240331_134306_Discord.jpg?ex=661b7cb8&is=660907b8&hm=f354147bd2d2f60a7f6940d50ebea9ced91e9d0d6891f01b33cff86adb4a66ed&

**Comment by NTDCore** [comment]
bro using walmart krampus

**Comment by MaxlaserTechAlt** [comment]
normal™️

**Comment by 7GrandDadPGN** [comment]
sorry I don't deal with THAT massive of a brain issue :trollface:
